// Generated by scripts/build-showcase.ts — run `npm run build:showcase`.
//
// `aspect` is read from each MP4's tkhd box, and `title` is derived from the
// filename. Both are preserved on re-run alongside `description` and `href`,
// so edit them freely here — only newly uploaded videos get appended.
//
// Don't change `id`: it's the key the script matches your edits against.

export interface ShowcaseItem {
  /** Stable key, derived from the R2 object name. */
  id: string;
  title: string;
  description?: string;
  /** Absolute URL on R2_PUBLIC_BASE_URL. */
  src: string;
  /** CSS aspect-ratio. Reserves the card's box before the video loads. */
  aspect: string;
  /** Optional link target for the card. */
  href?: string;
}

export const SHOWCASE_ITEMS: ShowcaseItem[] = [
  {
    id: 'bottom-menu-bar',
    title: 'Bottom Menu Bar',
    src: 'https://pub-52b0d9cec7c64f638ba3f33a29718fa6.r2.dev/BottomMenuBar.mp4',
    aspect: '29 / 45',
  },
  {
    id: 'bottom-menu-morph',
    title: 'Bottom Menu Morph',
    src: 'https://pub-52b0d9cec7c64f638ba3f33a29718fa6.r2.dev/BottomMenuMorph.mp4',
    aspect: '2652 / 2160',
  },
  {
    id: 'chat-ui01',
    title: 'Chat Interface',
    src: 'https://pub-52b0d9cec7c64f638ba3f33a29718fa6.r2.dev/ChatUI01.mp4',
    aspect: '3020 / 2160',
    href: '/blocks?slug=ai-chat&variation=default',
  },
  {
    id: 'ebay-ticker-animation',
    title: 'eBay Ticker',
    src: 'https://pub-52b0d9cec7c64f638ba3f33a29718fa6.r2.dev/EbayTickerAnimation.mp4',
    aspect: '2264 / 2160',
    href: '/blocks?slug=category-ticker&variation=vertical-marquee',
  },
  {
    id: 'image-morph',
    title: 'Image Morph',
    src: 'https://pub-52b0d9cec7c64f638ba3f33a29718fa6.r2.dev/ImageMorph.mp4',
    aspect: '80 / 43',
    href: '/blocks?slug=morphing-image-effect&variation=default',
  },
  {
    id: 'on-boarding-section-indiactor',
    title: 'Onboarding Indicator',
    src: 'https://pub-52b0d9cec7c64f638ba3f33a29718fa6.r2.dev/OnBoardingSectionIndiactor.mp4',
    aspect: '3004 / 2160',
    href: '/blocks?slug=onboarding-form&variation=default',
  },
  {
    id: 'payment-checkout',
    title: 'Payment Checkout',
    src: 'https://pub-52b0d9cec7c64f638ba3f33a29718fa6.r2.dev/PaymentCheckout.mp4',
    aspect: '1864 / 2160',
    href: '/blocks?slug=checkout-button&variation=default',
  },
  {
    id: 'pixel-dissolve-card',
    title: 'Pixel Dissolve Card',
    src: 'https://pub-52b0d9cec7c64f638ba3f33a29718fa6.r2.dev/PixelDissolveCard.mp4',
    aspect: '1652 / 2160',
    href: '/blocks?slug=pixel-dissolve-card&variation=default',
  },
  {
    id: 'product-card',
    title: 'Product Card',
    src: 'https://pub-52b0d9cec7c64f638ba3f33a29718fa6.r2.dev/ProductCard.mp4',
    aspect: '19 / 18',
    href: '/blocks?slug=product-card&variation=default',
  },
  {
    id: 'profile-card-morph',
    title: 'Profile Card Morph',
    src: 'https://pub-52b0d9cec7c64f638ba3f33a29718fa6.r2.dev/ProfileCardMorph.mp4',
    aspect: '1424 / 2160',
    href: '/blocks?slug=profile-card&variation=navbar',
  },
  {
    id: 'travelcard-scroll-animation',
    title: 'Travel Card Scroll',
    src: 'https://pub-52b0d9cec7c64f638ba3f33a29718fa6.r2.dev/TravelcardScrollAnimation.mp4',
    aspect: '3840 / 1900',
    href: '/blocks?slug=travel-card&variation=default',
  },
];
